version: "3.9"

services:
  blog-database:
    image: mongo
    ports:
      - "27017:27017"

  blog-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL="mongodb+srv://new_user:newuser@myblog.py7uva4.mongodb.net/?retryWrites=true&w=majority&appName=MyBlog"
    ports:
      - "3001:3001"
    depends_on:
      - blog-database

  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: https://blog-backend-861206262565.us-east4.run.app
    ports:
      - "3000:80"
    depends_on:
      - blog-backend
